import type { PrismaClient } from "@/generated/prisma/client";
import { SOURCE_KEYS } from "@/lib/nutrition-data/constants";

const TERMS_VERIFIED_AT = new Date("2026-08-12T00:00:00.000Z");

export async function seedDataSourceRegistry(prisma: PrismaClient) {
  const rows = [
    {
      sourceKey: SOURCE_KEYS.fixture,
      name: "Development fixture",
      provider: "internal-fixture",
      datasetName: "food-source-fixture-v1",
      datasetVersion: "2026.08.12",
      accessMethod: "fixture-file",
      license: "DEV_ONLY — not production nutrition data",
      licenseName: "DEV_ONLY",
      commercialUseAllowed: false,
      storageAllowed: false,
      transformationAllowed: false,
      customerDisplayAllowed: false,
      redistributionAllowed: false,
      licenseVerified: false,
      devOnly: true,
      status: "REJECTED" as const,
      notes: "Six-food engineering fixture. Not science grade. Forbidden in production.",
    },
    {
      sourceKey: SOURCE_KEYS.usda,
      name: "USDA FoodData Central",
      provider: "USDA ARS",
      datasetName: "FoodData Central Foundation Foods slice",
      datasetVersion: "2025-04-24",
      releaseDate: new Date("2025-04-24T00:00:00.000Z"),
      accessMethod: "api",
      license: "Public domain — CC0 1.0 Universal where applicable",
      licenseName: "CC0 1.0 Universal",
      licenseVersion: "1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      termsUrl: "https://fdc.nal.usda.gov/api-guide.html",
      sourceUrl: "https://fdc.nal.usda.gov/download-datasets.html",
      commercialUseAllowed: true,
      storageAllowed: true,
      transformationAllowed: true,
      customerDisplayAllowed: true,
      redistributionAllowed: true,
      licenseVerified: true,
      termsVerifiedAt: TERMS_VERIFIED_AT,
      verifiedBy: "phase2-legal-review",
      verificationMethod: "official-terms-review",
      verificationNotes:
        "USDA API guide states FDC data are public domain under CC0 1.0, intended for incorporation into applications, with attribution requested.",
      attributionText:
        "U.S. Department of Agriculture, Agricultural Research Service. FoodData Central, 2019. fdc.nal.usda.gov.",
      citationRequirement: "List FoodData Central as the source of the data.",
      devOnly: false,
      status: "APPROVED" as const,
      notes: "Primary production food-composition source for Phase 2 slice import.",
    },
    {
      sourceKey: SOURCE_KEYS.fineli,
      name: "Fineli Finnish Food Composition Database",
      provider: "Fineli / THL",
      datasetName: "Fineli",
      accessMethod: "download-api",
      license: "Creative Commons Attribution 4.0 International (CC BY 4.0)",
      licenseName: "CC BY 4.0",
      licenseVersion: "4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      termsUrl: "https://fineli.fi/fineli/en/avoin-data",
      sourceUrl: "https://fineli.fi/fineli/en/index",
      commercialUseAllowed: true,
      storageAllowed: true,
      transformationAllowed: true,
      customerDisplayAllowed: true,
      redistributionAllowed: true,
      licenseVerified: true,
      termsVerifiedAt: TERMS_VERIFIED_AT,
      verifiedBy: "phase2-legal-review",
      verificationMethod: "official-terms-review",
      verificationNotes:
        "Fineli open data page and THL open data license state CC BY 4.0 with attribution and no implied THL endorsement. Not imported in Phase 2.",
      attributionText: "Finnish Institute for Health and Welfare (THL), Fineli.",
      citationRequirement: "Credit THL and Fineli; do not imply THL endorsement.",
      devOnly: false,
      status: "REVIEW_REQUIRED" as const,
      notes: "Regional EU candidate. Terms appear permissive but not used in Phase 2 production slice.",
    },
    {
      sourceKey: SOURCE_KEYS.eurofir,
      name: "EuroFIR / FoodEXplorer",
      provider: "EuroFIR AISBL",
      datasetName: "FoodEXplorer",
      accessMethod: "membership-api",
      license: "Membership terms — redistribution not verified",
      licenseUrl: "https://www.eurofir.org/",
      sourceUrl: "https://www.eurofir.org/",
      commercialUseAllowed: false,
      storageAllowed: false,
      transformationAllowed: false,
      customerDisplayAllowed: false,
      redistributionAllowed: false,
      licenseVerified: false,
      devOnly: false,
      status: "FUTURE_OPTION" as const,
      notes: "Harmonization/comparison source only until explicit commercial reuse rights are confirmed.",
    },
    {
      sourceKey: SOURCE_KEYS.nnr2023,
      name: "Nordic Nutrition Recommendations 2023",
      provider: "NNR committee",
      datasetName: "NNR2023",
      accessMethod: "manual-review-import",
      license: "Publication copyright — numeric commercial redistribution not verified",
      sourceUrl: "https://nordicnutrition.org/",
      commercialUseAllowed: false,
      storageAllowed: false,
      transformationAllowed: false,
      customerDisplayAllowed: false,
      redistributionAllowed: false,
      licenseVerified: false,
      devOnly: false,
      status: "REVIEW_REQUIRED" as const,
      notes: "Scientific reference candidate only. Do not embed numeric tables without explicit reuse permission.",
    },
    {
      sourceKey: SOURCE_KEYS.efsaDrv,
      name: "EFSA Dietary Reference Values",
      provider: "EFSA",
      datasetName: "DRV framework",
      datasetVersion: "2017-e15121",
      accessMethod: "manual-review-import",
      license:
        "© European Food Safety Authority, 2017 — Reproduction is authorised provided the source is acknowledged.",
      licenseName: "EFSA 2017 DRV Summary Report copyright notice",
      licenseVersion: "2017-e15121",
      licenseUrl:
        "https://www.efsa.europa.eu/sites/default/files/2017_09_DRVs_summary_report.pdf",
      termsUrl: "https://www.efsa.europa.eu/en/legalnotice",
      sourceUrl:
        "https://www.efsa.europa.eu/sites/default/files/2017_09_DRVs_summary_report.pdf",
      commercialUseAllowed: true,
      storageAllowed: true,
      transformationAllowed: true,
      customerDisplayAllowed: true,
      redistributionAllowed: true,
      licenseVerified: true,
      termsVerifiedAt: TERMS_VERIFIED_AT,
      verifiedBy: "phase2-official-terms-review",
      verificationMethod: "official-document-copyright-notice",
      verificationNotes:
        "EFSA 2017 DRV Summary Report (e15121): 'Reproduction is authorised provided the source is acknowledged.' Website legal notice: 'Re-use is authorised, provided that EFSA is acknowledged as the source of the material.'",
      attributionText:
        "EFSA (European Food Safety Authority), 2017. Dietary reference values for nutrients: Summary report. EFSA supporting publication 2017:e15121.",
      citationRequirement: "Acknowledge EFSA as source (doi:10.2903/sp.efsa.2017.e15121).",
      devOnly: false,
      status: "APPROVED" as const,
      notes: "Production requirement reference source. Numeric slice imported to RequirementSet efsa-drv-eu-2017-v1.",
    },
  ];

  for (const row of rows) {
    await prisma.foodDataSource.upsert({
      where: { sourceKey: row.sourceKey },
      create: row,
      update: {
        name: row.name,
        provider: row.provider,
        datasetName: row.datasetName,
        datasetVersion: row.datasetVersion ?? null,
        releaseDate: row.releaseDate ?? null,
        accessMethod: row.accessMethod,
        license: row.license,
        licenseName: row.licenseName ?? null,
        licenseVersion: row.licenseVersion ?? null,
        licenseUrl: row.licenseUrl ?? null,
        termsUrl: row.termsUrl ?? null,
        sourceUrl: row.sourceUrl ?? null,
        commercialUseAllowed: row.commercialUseAllowed,
        storageAllowed: row.storageAllowed,
        transformationAllowed: row.transformationAllowed,
        customerDisplayAllowed: row.customerDisplayAllowed,
        redistributionAllowed: row.redistributionAllowed,
        licenseVerified: row.licenseVerified,
        termsVerifiedAt: row.termsVerifiedAt ?? null,
        verifiedBy: row.verifiedBy ?? null,
        verificationMethod: row.verificationMethod ?? null,
        verificationNotes: row.verificationNotes ?? null,
        attributionText: row.attributionText ?? null,
        citationRequirement: row.citationRequirement ?? null,
        devOnly: row.devOnly,
        status: row.status,
        notes: row.notes,
      },
    });
  }

}
